# Generated by Django 4.0.2 on 2022-02-23 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReadConfig',
            fields=[
                ('config_key', models.CharField(max_length=24, primary_key=True, serialize=False)),
                ('config_value', models.CharField(max_length=256)),
            ],
        ),
    ]
